<html>
<head>
<title>email test</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
</head>

<body>
<h1>Email Test</h1>
<?php 
$to = "rmitchell@essexheritage.org";
$subject = "eis rebuilt";
$body = "generated by days_action";
$headers = "From: rmitchell@essexheritage.org";

mail ($to, $subject, $body, $headers);

?>
<p><a href="index.php">Return</a></p>
<p>&nbsp; </p>
</body>
</html>
